### ISSUE TITLE
Make it easy to add libgdx extension libs like freetype and bullet.

### ISSUE THREAD

**Issue by ajhager** [ajhager/libgdx-sbt-project.g8#56] opened 2013-09-30 00:18 UTC

**Comment by aginiewicz** [comment] 2013-12-30 10:24
I was thinking about it (I will need freetype for my project pretty soon) and I think that https://github.com/ajhager/libgdx-sbt-project.g8/issues/48 will be critical here - it would be then simple changing key from false to true and running update to extract needed natives.

**Comment by aginiewicz** [comment] 2014-07-07 14:29
Technically now it is only adding line to maven dependencies and native extractions - I guess it is as simple as it can get, it only needs wiki documentation now. Don't you think?

**Comment by aginiewicz** [comment] 2014-07-07 16:25
duplicate of https://github.com/ajhager/libgdx-sbt-project.g8/issues/53

**Closed as completed by aginiewicz** 2014-07-07 16:25 UTC
